/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    users: User;
    coaches: Coach;
    services: Service;
    courses: Course;
    spaces: Space;
    subscriptions: Subscription;
    bookings: Booking;
    payments: Payment;
    'payment-links': PaymentLink;
    coupons: Coupon;
    'coupon-usages': CouponUsage;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    coaches: CoachesSelect<false> | CoachesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    spaces: SpacesSelect<false> | SpacesSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    'payment-links': PaymentLinksSelect<false> | PaymentLinksSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    'coupon-usages': CouponUsagesSelect<false> | CouponUsagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin | User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  firstName: string;
  lastName: string;
  role: 'superadmin' | 'admin' | 'support';
  isActive?: boolean | null;
  authProvider?: 'google' | null;
  authProviderUserId?: string | null;
  avatarUrl?: string | null;
  lastSocialLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  phone?: string | null;
  address?: string | null;
  city?: string | null;
  zipCode?: string | null;
  /**
   * Indicateur de compatibilité frontend (hérité)
   */
  isAdmin?: boolean | null;
  locale?: ('en' | 'fr') | null;
  timezone?: string | null;
  /**
   * Dernier fournisseur social utilisé pour s'authentifier.
   */
  authProvider?: 'google' | null;
  /**
   * Identifiant utilisateur fournisseur (sujet Google).
   */
  authProviderUserId?: string | null;
  emailVerifiedAt?: string | null;
  avatarUrl?: string | null;
  marketingOptIn?: boolean | null;
  /**
   * Notes internes (non visibles par le client)
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaches".
 */
export interface Coach {
  id: number;
  displayName: string;
  slug: string;
  title: string;
  email: string;
  phone?: string | null;
  marketingBio?: string | null;
  experience?: string | null;
  quote?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Photo du coach utilisee dans le catalogue et les fiches.
   */
  profilePicture?: (number | null) | Media;
  cardGradient?: ('violet_rose' | 'vert_emeraude' | 'bleu_cyan') | null;
  category: 'fitness' | 'padel' | 'wellness';
  timezone: string;
  specialties?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  certifications?:
    | {
        name: string;
        issuer?: string | null;
        year?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Disponibilites hebdomadaires recurrents
   */
  availability?:
    | {
        dayOfWeek: '1' | '2' | '3' | '4' | '5' | '6' | '0';
        /**
         * HH:mm
         */
        startTime: string;
        /**
         * HH:mm
         */
        endTime: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Exceptions ponctuelles (jours feries, horaires speciaux)
   */
  availabilityExceptions?:
    | {
        date: string;
        isAvailable?: boolean | null;
        /**
         * HH:mm (requis si disponible)
         */
        startTime?: string | null;
        /**
         * HH:mm (requis si disponible)
         */
        endTime?: string | null;
        id?: string | null;
      }[]
    | null;
  isActive?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  shortDescription?: string | null;
  /**
   * Image d'affichage du service
   */
  image?: (number | null) | Media;
  /**
   * Prix en centimes (ex : 5000 = 50,00 €)
   */
  priceCents: number;
  currency: 'usd' | 'eur' | 'cad';
  durationMinutes: number;
  bufferBeforeMinutes?: number | null;
  bufferAfterMinutes?: number | null;
  eligibleCoaches?: (number | Coach)[] | null;
  maxAdvanceBookingDays?: number | null;
  minAdvanceBookingHours?: number | null;
  cancellationPolicyHours?: number | null;
  stripeProductId?: string | null;
  stripePriceId?: string | null;
  isActive?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  slug: string;
  title: string;
  category: 'fitness' | 'bien_etre' | 'padel' | 'force';
  description: string;
  duration: string;
  difficulty: 'debutant' | 'intermediaire' | 'avance';
  maxParticipants: number;
  image?: (number | null) | Media;
  benefits?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  equipment?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  price: number;
  gradient:
    | 'from-orange-400 to-red-500'
    | 'from-blue-400 to-purple-500'
    | 'from-green-400 to-emerald-500'
    | 'from-red-400 to-pink-500'
    | 'from-purple-400 to-indigo-500'
    | 'from-yellow-400 to-orange-500';
  isActive?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "spaces".
 */
export interface Space {
  id: number;
  slug: string;
  name: string;
  category: 'musculation_cardio' | 'sport_raquette' | 'relaxation_recovery' | 'training_specialise' | 'relaxation';
  description: string;
  features?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  equipment?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  capacity: string;
  hours: string;
  image?: (number | null) | Media;
  /**
   * Images secondaires pour l apercu galerie.
   */
  gallery?: (number | Media)[] | null;
  amenities?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  specifications: {
    surface: string;
    temperature: string;
    ventilation: string;
    sound: string;
  };
  gradient:
    | 'from-blue-500 to-purple-600'
    | 'from-green-500 to-emerald-600'
    | 'from-pink-500 to-rose-600'
    | 'from-orange-500 to-red-600'
    | 'from-cyan-500 to-blue-600';
  isActive?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: number;
  slug: string;
  title: string;
  subtitle: string;
  offerLevel: 'fitness' | 'dynamique' | 'premium' | 'espace';
  price: number;
  period: 'mois' | 'an';
  registrationFee: number;
  isPopular?: boolean | null;
  isPremium?: boolean | null;
  benefits?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  description: string;
  gradient:
    | 'from-luxury-black to-luxury-black'
    | 'from-luxury-black to-luxury-purple'
    | 'from-luxury-black to-luxury-green'
    | 'from-luxury-black via-luxury-green to-luxury-purple';
  icon: '💪' | '🧘' | '⭐' | '🏆';
  ctaText: string;
  restrictions?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  isActive?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  user: number | User;
  coach: number | Coach;
  service: number | Service;
  startTime: string;
  endTime: string;
  timezone: string;
  status: 'pending_payment' | 'confirmed' | 'completed' | 'cancelled' | 'canceled' | 'no_show' | 'failed_payment';
  paymentStatus: 'unpaid' | 'paid' | 'refunded' | 'failed' | 'expired';
  stripeCheckoutSessionId?: string | null;
  stripePaymentIntentId?: string | null;
  payment?: (number | null) | Payment;
  coupon?: (number | null) | Coupon;
  priceCents: number;
  discountCents?: number | null;
  totalCents: number;
  currency: 'usd' | 'eur' | 'cad';
  customerNotes?: string | null;
  internalNotes?: string | null;
  cancellationReason?: string | null;
  cancelledAt?: string | null;
  meetingUrl?: string | null;
  reminderSent48h?: boolean | null;
  reminderSent24h?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  user: number | User;
  booking?: (number | null) | Booking;
  stripePaymentIntentId?: string | null;
  stripeCheckoutSessionId?: string | null;
  stripeChargeId?: string | null;
  amountCents: number;
  currency: 'usd' | 'eur' | 'cad';
  status: 'pending' | 'succeeded' | 'failed' | 'refunded' | 'partially_refunded';
  refundedAmountCents?: number | null;
  failureReason?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  code: string;
  description?: string | null;
  discountType: 'percentage' | 'fixed';
  discountValue: number;
  /**
   * Utilisations totales pour tous les clients. Laisser vide pour illimité.
   */
  maxRedemptions?: number | null;
  maxRedemptionsPerUser?: number | null;
  redemptionCount?: number | null;
  minOrderCents?: number | null;
  /**
   * Laisser vide pour appliquer à tous les services
   */
  applicableServices?: (number | Service)[] | null;
  startsAt?: string | null;
  expiresAt?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-links".
 */
export interface PaymentLink {
  id: number;
  name: string;
  description?: string | null;
  amountCents: number;
  currency: 'usd' | 'eur' | 'cad';
  service?: (number | null) | Service;
  coach?: (number | null) | Coach;
  stripePaymentLinkId?: string | null;
  stripeUrl?: string | null;
  maxUses?: number | null;
  useCount?: number | null;
  expiresAt?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupon-usages".
 */
export interface CouponUsage {
  id: number;
  coupon: number | Coupon;
  user: number | User;
  booking?: (number | null) | Booking;
  discountAppliedCents: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'coaches';
        value: number | Coach;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'spaces';
        value: number | Space;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: number | Subscription;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'payment-links';
        value: number | PaymentLink;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null)
    | ({
        relationTo: 'coupon-usages';
        value: number | CouponUsage;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  isActive?: T;
  authProvider?: T;
  authProviderUserId?: T;
  avatarUrl?: T;
  lastSocialLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phone?: T;
  address?: T;
  city?: T;
  zipCode?: T;
  isAdmin?: T;
  locale?: T;
  timezone?: T;
  authProvider?: T;
  authProviderUserId?: T;
  emailVerifiedAt?: T;
  avatarUrl?: T;
  marketingOptIn?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaches_select".
 */
export interface CoachesSelect<T extends boolean = true> {
  displayName?: T;
  slug?: T;
  title?: T;
  email?: T;
  phone?: T;
  marketingBio?: T;
  experience?: T;
  quote?: T;
  bio?: T;
  profilePicture?: T;
  cardGradient?: T;
  category?: T;
  timezone?: T;
  specialties?:
    | T
    | {
        value?: T;
        id?: T;
      };
  certifications?:
    | T
    | {
        name?: T;
        issuer?: T;
        year?: T;
        id?: T;
      };
  availability?:
    | T
    | {
        dayOfWeek?: T;
        startTime?: T;
        endTime?: T;
        id?: T;
      };
  availabilityExceptions?:
    | T
    | {
        date?: T;
        isAvailable?: T;
        startTime?: T;
        endTime?: T;
        id?: T;
      };
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  shortDescription?: T;
  image?: T;
  priceCents?: T;
  currency?: T;
  durationMinutes?: T;
  bufferBeforeMinutes?: T;
  bufferAfterMinutes?: T;
  eligibleCoaches?: T;
  maxAdvanceBookingDays?: T;
  minAdvanceBookingHours?: T;
  cancellationPolicyHours?: T;
  stripeProductId?: T;
  stripePriceId?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  category?: T;
  description?: T;
  duration?: T;
  difficulty?: T;
  maxParticipants?: T;
  image?: T;
  benefits?:
    | T
    | {
        value?: T;
        id?: T;
      };
  equipment?:
    | T
    | {
        value?: T;
        id?: T;
      };
  price?: T;
  gradient?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "spaces_select".
 */
export interface SpacesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  category?: T;
  description?: T;
  features?:
    | T
    | {
        value?: T;
        id?: T;
      };
  equipment?:
    | T
    | {
        value?: T;
        id?: T;
      };
  capacity?: T;
  hours?: T;
  image?: T;
  gallery?: T;
  amenities?:
    | T
    | {
        value?: T;
        id?: T;
      };
  specifications?:
    | T
    | {
        surface?: T;
        temperature?: T;
        ventilation?: T;
        sound?: T;
      };
  gradient?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  subtitle?: T;
  offerLevel?: T;
  price?: T;
  period?: T;
  registrationFee?: T;
  isPopular?: T;
  isPremium?: T;
  benefits?:
    | T
    | {
        value?: T;
        id?: T;
      };
  description?: T;
  gradient?: T;
  icon?: T;
  ctaText?: T;
  restrictions?:
    | T
    | {
        value?: T;
        id?: T;
      };
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  user?: T;
  coach?: T;
  service?: T;
  startTime?: T;
  endTime?: T;
  timezone?: T;
  status?: T;
  paymentStatus?: T;
  stripeCheckoutSessionId?: T;
  stripePaymentIntentId?: T;
  payment?: T;
  coupon?: T;
  priceCents?: T;
  discountCents?: T;
  totalCents?: T;
  currency?: T;
  customerNotes?: T;
  internalNotes?: T;
  cancellationReason?: T;
  cancelledAt?: T;
  meetingUrl?: T;
  reminderSent48h?: T;
  reminderSent24h?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  user?: T;
  booking?: T;
  stripePaymentIntentId?: T;
  stripeCheckoutSessionId?: T;
  stripeChargeId?: T;
  amountCents?: T;
  currency?: T;
  status?: T;
  refundedAmountCents?: T;
  failureReason?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-links_select".
 */
export interface PaymentLinksSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  amountCents?: T;
  currency?: T;
  service?: T;
  coach?: T;
  stripePaymentLinkId?: T;
  stripeUrl?: T;
  maxUses?: T;
  useCount?: T;
  expiresAt?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  description?: T;
  discountType?: T;
  discountValue?: T;
  maxRedemptions?: T;
  maxRedemptionsPerUser?: T;
  redemptionCount?: T;
  minOrderCents?: T;
  applicableServices?: T;
  startsAt?: T;
  expiresAt?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupon-usages_select".
 */
export interface CouponUsagesSelect<T extends boolean = true> {
  coupon?: T;
  user?: T;
  booking?: T;
  discountAppliedCents?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}